### ISSUE TITLE
NPM run build issue

### ISSUE THREAD

**Issue by Laukage** [Cryptkeeper/Minetrack#261]
I can't get minetrack to run on this machine for some reason..
Not sure if its because it is arm based cpu?

Stack trace when running "NPM run build"
https://mclo.gs/XQNIlbI

**Comment by hugmanrique** [comment]
According to https://github.com/parcel-bundler/source-map/issues/33, the [Rust rewrite](https://github.com/parcel-bundler/source-map/pull/52) of source-map should fix this issue. The fix should be included in Parcel `2.0.0-beta.3.1`, but I'm not sure. Could you try pining parcel to that version in the `package.json` file, run `npm i`, and try again?

**Comment by Laukage** [comment]
> According to [parcel-bundler/source-map#33](https://github.com/parcel-bundler/source-map/issues/33), the [Rust rewrite](https://github.com/parcel-bundler/source-map/pull/52) of source-map should fix this issue. The fix should be included in Parcel `2.0.0-beta.3.1`, but I'm not sure. Could you try pining parcel to that version in the `package.json` file, run `npm i`, and try again?

I'm not sure what any of that means xD

**Comment by hugmanrique** [comment]
My bad, replace `beta.2` by `beta.3.1` in this line https://github.com/Cryptkeeper/Minetrack/blob/41060dcaa5cc4c9bedd125438acfc419d0bb1764/package.json#L48, then run `npm i` and try building the client (as specified in the README file, i.e. as you did when filling this issue). Does the same error message appear?

**Comment by Laukage** [comment]
i replaced "Beta.2" with "Beta.3.1.
Ran "NPM I"
then i ran "npm run build"

still getting somewhat the same error:
https://mclo.gs/dxdFEdz

**Comment by Laukage** [comment]
> My bad, replace `beta.2` by `beta.3.1` in this line
> 
> https://github.com/Cryptkeeper/Minetrack/blob/41060dcaa5cc4c9bedd125438acfc419d0bb1764/package.json#L48
> 
> , then run `npm i` and try building the client (as specified in the README file, i.e. as you did when filling this issue). Does the same error message appear?

Do you happen to know what my issue might be or have any troubleshooting steps i can take?

**Comment by hugmanrique** [comment]
There's no need to ask for etas, we will reply when available. Anyways, we need the `@parcel/source-map` version. Can you post the output of `npm view @parcel/source-map`? If it returns `2.0.0-alpha.4.18`, we will post an issue on the upstream project. Otherwise, you can try explicitly adding the latest version (mentioned before) of `@parcel/source-map` to your `package.json` file and run `npm i` again.

**Comment by Laukage** [comment]
> There's no need to ask for etas, we will reply when available. Anyways, we need the `@parcel/source-map` version. Can you post the output of `npm view @parcel/source-map`? If it returns `2.0.0-alpha.4.18`, we will post an issue on the upstream project. Otherwise, you can try explicitly adding the latest version (mentioned before) of `@parcel/source-map` to your `package.json` file and run `npm i` again.

Sorry, i wasn't sure if you had seen it cuz it wasn't a reply - won't happen again.

I'm assuming this means i have version 2.0.0-rc.4
![image](https://user-images.githubusercontent.com/46964809/122265505-1f1ab080-ced9-11eb-8d3c-7674fc4a0736.png)

**Comment by hugmanrique** [comment]
Alright, now we're getting a different error, that's good! (well, not 100% good). `node-sqlite3` doesn't provide precompiled binaries for `linux-arm64` (see https://github.com/mapbox/node-sqlite3/issues/1413). You will need to build from source which, by reading the linked issue, seems to require python 2. Once installed, try `npm i` again.

**Comment by Laukage** [comment]
> Alright, now we're getting a different error, that's good! (well, not 100% good). `node-sqlite3` doesn't provide precompiled binaries for `linux-arm64` (see [mapbox/node-sqlite3#1413](https://github.com/mapbox/node-sqlite3/issues/1413)). You will need to build from source which, by reading the linked issue, seems to require python 2. Once you have python installed, try `npm i` again.

That error has now gone away since i have Python2 installed, i get past "NPM I"
but now when i run "npm run build" i get this error...
![image](https://user-images.githubusercontent.com/46964809/122279262-239a9580-cee8-11eb-8ae5-99e7b70d5cf1.png)

**Comment by hugmanrique** [comment]
Ah, the same error is back. Will open an issue there requesting an arm64 build soon. For now, I suggest running Minetrack on x86.

**Comment by Cryptkeeper** [comment]
Until there is a sqlite3 arm build available, you will need to run on x86-64.
